SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[frwGROUPPERMISSIONS] (
		[GROUPPERMISSION_GROUPID]     [int] NOT NULL,
		[GROUPPERMISSION_OBJECT]      [varchar](50) COLLATE Arabic_CI_AS NOT NULL,
		[GROUPPERMISSION_ACCESS]      [tinyint] NOT NULL,
		[GUID]                        [uniqueidentifier] NOT NULL ROWGUIDCOL,
		CONSTRAINT [PK_frwGROUPPERMISSIONS]
		PRIMARY KEY
		CLUSTERED
		([GROUPPERMISSION_GROUPID], [GROUPPERMISSION_OBJECT], [GROUPPERMISSION_ACCESS])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[frwGROUPPERMISSIONS]
	ADD
	CONSTRAINT [DF__frwGROUPPE__GUID__160F4887]
	DEFAULT (newid()) FOR [GUID]
GO
ALTER TABLE [dbo].[frwGROUPPERMISSIONS]
	WITH CHECK
	ADD CONSTRAINT [FK_frwGROUPPERMISSIONS_frwGROUPS]
	FOREIGN KEY ([GROUPPERMISSION_GROUPID]) REFERENCES [dbo].[frwGROUPS] ([GROUP_ID])
	ON DELETE CASCADE
	ON UPDATE CASCADE
ALTER TABLE [dbo].[frwGROUPPERMISSIONS]
	CHECK CONSTRAINT [FK_frwGROUPPERMISSIONS_frwGROUPS]

GO
ALTER TABLE [dbo].[frwGROUPPERMISSIONS]
	WITH CHECK
	ADD CONSTRAINT [FK_frwGROUPPERMISSIONS_frwOBJECTS]
	FOREIGN KEY ([GROUPPERMISSION_OBJECT]) REFERENCES [dbo].[frwObjects] ([Object_Name])
	ON DELETE CASCADE
	ON UPDATE CASCADE
ALTER TABLE [dbo].[frwGROUPPERMISSIONS]
	CHECK CONSTRAINT [FK_frwGROUPPERMISSIONS_frwOBJECTS]

GO
CREATE UNIQUE NONCLUSTERED INDEX [IXGUID_frwGROUPPERMISSIONS]
	ON [dbo].[frwGROUPPERMISSIONS] ([GUID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[frwGROUPPERMISSIONS] SET (LOCK_ESCALATION = TABLE)
GO
