SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[frwGROUPS] (
		[GROUP_ID]        [int] IDENTITY(1, 1) NOT NULL,
		[GROUP_NAME]      [varchar](20) COLLATE Arabic_CI_AS NULL,
		[LAST_UPDATE]     [datetime] NULL,
		CONSTRAINT [PK_frwGROUPS]
		PRIMARY KEY
		CLUSTERED
		([GROUP_ID])
	ON [PRIMARY]
)
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_frwGROUPS]
	ON [dbo].[frwGROUPS] ([GROUP_NAME])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[frwGROUPS] SET (LOCK_ESCALATION = TABLE)
GO
